export const SAMPLE_EXAMS = {
  "cloud-foundations": {
    id: "cloud-foundations",
    title: "Fundamentos de Cloud Computing",
    vendor: "Muestra",
    icon: "☁️",
    description: "Conceptos básicos de cómputo en la nube, modelos de servicio y despliegue.",
    passingScorePercentage: 70,
    timeLimitMinutes: 10,
    questions: [
      {
        id: 1,
        type: "multiple_choice",
        question: "¿Cuál de los siguientes es un modelo de servicio de nube (no de despliegue)?",
        options: ["IaaS", "Nube privada", "Nube híbrida", "Nube comunitaria"],
        correctAnswer: 0,
        explanation: "IaaS, PaaS y SaaS son modelos de servicio; privada/pública/híbrida son modelos de despliegue.",
      },
      {
        id: 2,
        type: "true_false",
        question: "En el modelo SaaS, el cliente es responsable de administrar el sistema operativo del servidor.",
        correctAnswer: false,
        explanation: "En SaaS el proveedor administra toda la pila, incluido el sistema operativo.",
      },
      {
        id: 3,
        type: "multiple_choice",
        question: "¿Qué característica permite escalar recursos automáticamente según la demanda?",
        options: ["Elasticidad", "Virtualización", "Multi-tenencia", "Redundancia geográfica"],
        correctAnswer: 0,
        explanation: "La elasticidad es la capacidad de escalar recursos hacia arriba o abajo según la demanda.",
      },
      {
        id: 4,
        type: "open",
        question: "Explica brevemente la diferencia entre escalabilidad vertical y horizontal.",
        referenceAnswer: "Vertical: agregar recursos a un mismo servidor. Horizontal: agregar más servidores.",
      },
      {
        id: 5,
        type: "true_false",
        question: "Un modelo de responsabilidad compartida significa que el proveedor de la nube es responsable de toda la seguridad.",
        correctAnswer: false,
        explanation: "El proveedor asegura la infraestructura; el cliente sigue siendo responsable de datos, accesos y configuración.",
      },
      {
        id: 6,
        type: "multiple_choice",
        question: "¿Cuál es una ventaja típica de usar contenedores frente a máquinas virtuales tradicionales?",
        options: [
          "Inicio más rápido y menor consumo de recursos",
          "Aislamiento total del kernel del sistema operativo",
          "Eliminan la necesidad de redes virtuales",
          "No requieren orquestación",
        ],
        correctAnswer: 0,
        explanation: "Los contenedores comparten el kernel del host, por lo que inician más rápido y consumen menos recursos que una VM completa.",
      },
    ],
  },
  "networking-basics": {
    id: "networking-basics",
    title: "Fundamentos de Redes",
    vendor: "Muestra",
    icon: "🌐",
    description: "Modelo OSI, direccionamiento IP y conceptos esenciales de conectividad.",
    passingScorePercentage: 70,
    timeLimitMinutes: 10,
    questions: [
      {
        id: 1,
        type: "multiple_choice",
        question: "¿En qué capa del modelo OSI operan los switches tradicionales?",
        options: ["Capa 2 (Enlace de datos)", "Capa 3 (Red)", "Capa 4 (Transporte)", "Capa 7 (Aplicación)"],
        correctAnswer: 0,
        explanation: "Los switches tradicionales conmutan tramas usando direcciones MAC, en la capa de enlace de datos.",
      },
      {
        id: 2,
        type: "true_false",
        question: "El protocolo TCP garantiza la entrega ordenada de los paquetes.",
        correctAnswer: true,
        explanation: "TCP es orientado a conexión y garantiza entrega ordenada y confirmada.",
      },
      {
        id: 3,
        type: "multiple_choice",
        question: "¿Cuántas direcciones host utilizables tiene una subred /30?",
        options: ["2", "4", "6", "8"],
        correctAnswer: 0,
        explanation: "Una /30 tiene 4 direcciones totales, menos red y broadcast, quedan 2 utilizables.",
      },
      {
        id: 4,
        type: "open",
        question: "¿Qué función cumple un servidor DNS en una red?",
        referenceAnswer: "Traduce nombres de dominio legibles a direcciones IP.",
      },
      {
        id: 5,
        type: "true_false",
        question: "NAT permite que múltiples dispositivos con IPs privadas compartan una sola IP pública.",
        correctAnswer: true,
        explanation: "Esa es justamente la función principal de NAT (Network Address Translation).",
      },
      {
        id: 6,
        type: "multiple_choice",
        question: "¿Qué protocolo se usa típicamente para asignar direcciones IP automáticamente?",
        options: ["DHCP", "SMTP", "FTP", "ICMP"],
        correctAnswer: 0,
        explanation: "DHCP asigna configuración IP automáticamente a los dispositivos de una red.",
      },
    ],
  },
};
